name: Build FE Staging
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-prereleased:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, ubuntu-runner-1]
    # needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Get the version from Tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: pelabuhan.alterra.dev

      - name: Build & push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/sibs-v2/icc-dashboard:${{ steps.get_version.outputs.VERSION }}
          build-args: |
            VUE_APP_DEFAULT_AUTH=${{ secrets.VUE_APP_DEFAULT_AUTH_STAGING }}
            VUE_APP_APIKEY=${{ secrets.VUE_APP_APIKEY_STAGING }}
            VUE_APP_AUTHDOMAIN=${{ secrets.VUE_APP_AUTHDOMAIN_STAGING }}
            VUE_APP_DATABASEURL=${{ secrets.VUE_APP_DATABASEURL_STAGING }}
            VUE_APP_PROJECTId=${{ secrets.VUE_APP_PROJECTId_STAGING }}
            VUE_APP_STORAGEBUCKET=${{ secrets.VUE_APP_STORAGEBUCKET_STAGING }}
            VUE_APP_MESSAGINGSENDERID=${{ secrets.VUE_APP_MESSAGINGSENDERID_STAGING }}
            VUE_APP_APPId=${{ secrets.VUE_APP_APPId_STAGING }}
            VUE_APP_MEASUREMENTID=${{ secrets.VUE_APP_MEASUREMENTID_STAGING }}
      - name: Setup GCP / Kubectl
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: "290.0.1"
          
      - name: Setup Kubeconfig
        run: |
          cat >> ./kubeconfig_icc <<END 
          ${{ secrets.KUBECONFIG_RARA }}
          END
          
      - name: Deploy
        run: |
          kubectl --kubeconfig ./kubeconfig_icc -n icc set image deployment/icc-fe icc-fe=pelabuhan.alterra.dev/sibs-v2/icc-dashboard:${{ steps.get_version.outputs.VERSION }} --record
          
      - name: Clean
        run: |
          rm -rf ./kubeconfig_icc
