name: Build FE Staging
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-and-deploy:
    runs-on: [self-hosted, ubuntu-runner-1] # test custom runner
    strategy:
      matrix:
        go-version: [1.14.x]
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Dev
        # if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_URL }}

      - name: Outputs Tag Version
        id: vars
        run: |
          if [[ ${GITHUB_REF#refs/heads/} == 'main' ]]; then
            echo "::set-output name=version::$(git rev-parse --short HEAD)"
          else
            VERSION=$(git describe --tags) # will fail if never tagged
            echo "::set-output name=version::${VERSION}"
          fi
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build and push docker images to docker registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: pelabuhan.alterra.dev/sibs-v2/icc-dashboard:${{ steps.vars.outputs.version }}
