name: Test Build Deploy Staging

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-deploy-staging:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: pelabuhan.alterra.dev
          username: ${{ secrets.HARBOR_U }}
          password: ${{ secrets.HARBOR_P }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: pelabuhan.alterra.dev/sibs-v2/icc-dashboard:${{ github.sha }}
          build-args: |
            VUE_APP_DEFAULT_AUTH=${{ secrets.VUE_APP_DEFAULT_AUTH_STAGING }}
            VUE_APP_APIKEY=${{ secrets.VUE_APP_APIKEY_STAGING }}
            VUE_APP_AUTHDOMAIN=${{ secrets.VUE_APP_AUTHDOMAIN_STAGING }}
            VUE_APP_DATABASEURL=${{ secrets.VUE_APP_DATABASEURL_STAGING }}
            VUE_APP_PROJECTId=${{ secrets.VUE_APP_PROJECTId_STAGING }}
            VUE_APP_STORAGEBUCKET=${{ secrets.VUE_APP_STORAGEBUCKET_STAGING }}
            VUE_APP_MESSAGINGSENDERID=${{ secrets.VUE_APP_MESSAGINGSENDERID_STAGING }}
            VUE_APP_APPId=${{ secrets.VUE_APP_APPId_STAGING }}
            VUE_APP_MEASUREMENTID=${{ secrets.VUE_APP_MEASUREMENTID_STAGING }}
      - name: Setup GCP / Kubectl
        uses: google-github-actions/setup-gcloud@v0

      - name: Setup Kubeconfig
        run: |
          cat >> ./kubeconfig_icc <<END 
          ${{ secrets.KUBECONFIG_RARA }}
          END

      - name: Deploy
        run: |
           kubectl --kubeconfig ./kubeconfig_icc -n icc set image deployment/icc-fe icc-fe=${{ secrets.IMAGE }}:${{ github.sha }} --record

      - name: Clean
        run: |
          rm -rf ./kubeconfig_icc
